config/routes.rb
Rails.application.routes.draw do

   #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'root#index'
   resources :books, only: [:show]
   resources :logs, only: [:destroy]
   resources :users do
     resources :logs, only: [:create, :index]
   end
   resources :categories, only: [:index,:show]
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   namespace :admin do
     resources :books
     resources :categories, only: [:new, :create]
     resources :logs, only: [:index,:show,:update,:destroy] do
       post 'toggle_confirm'
     end
   end
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :logs, dependent: :destroy
  belongs_to :category
  scope :get_by_title, ->(title){
    where("title like ?", "%#{title}%")
  }
  scope :is_stocked, ->{ where("count > 0") }
  scope :is_published, ->{ where(is_published: 1)}
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  before_action :book_params, only:[:create]
  before_action :set_book, only:[:show, :edit, :update, :destroy]

  include AdminHelper

  def index
    @books = Book.all
  end

  def show
  end

  def edit
  end

  def new
   @admin_book = Book.new 
  end


  def create
   Book.create(book_params)  
   redirect_to admin_books_path
  end

  def update
   @book= Book.find(params[:id])
   @book.update(book_params)  
   redirect_to admin_books_path, notice: "更新しました"
  end

  def destroy
    if @book.delete
      redirect_to admin_books_path, notice: "削除しました"
    else
      redirect_to admin_books_path, notice: "削除できませんでした"
    end
  end

    private
      def set_book
        @book = Book.find_by(id: params[:id])
      end

      def book_params
        params.require(:book).permit!
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book
  def show
    session.delete(:requested_book_id)
    if current_user && log = Log.get_current_user_log(current_user.id, params[:id]).first
      @log = log
    else
      @log = Log.new
    end
  end

  private
    def set_book
      @book = Book.find_by(id: params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper

  def book_or_not_btn
    if current_user.book
    end
  end

end

app/views/admin/books/edit.html.slim
div.book_edit_container
  div.img_container
    = image_tag(@book.image.url)

  ul.book_new_form
    = form_for @book, url: {action: "update"} do |f|
      li 
        = f.label :title, "タイトル"
        = f.text_field :title
      li
        = f.label :image, "画像"
        = f.file_field :image
      li
        = f.label :author, "著者"
        = f.text_field :author
      li
        = f.label :price, "値段"
        = f.text_field :price
      li
        = f.label :category_id, "カテゴリー"
        = f.select :category_id , Category.all_ary
      li
        = f.label :count, "個数"
        = f.text_field :count
      li
        = f.label :is_published, "公開可否"
        = f.select :is_published, [["公開", 1], ["非公開", 0]]
      li
        = f.submit("更新する")
      li
        = link_to "削除する", admin_book_path(@book.id), class: "cancel_button", method: :delete 

app/views/admin/books/index.html.slim
h1.head 教科書一覧
div.admin_book_index
  = render partial: "books_index", locals: {books: Book.all}

app/views/admin/books/new.html.slim
ul.book_new_form
  = form_for @admin_book, url: {action: "create"} do |f|
    li
      = f.label :title, "タイトル"
      = f.text_field :title
    li
      = f.label :image, "画像"
      = f.file_field :image
    li
      = f.label :author, "著者"
      = f.text_field :author
    li
      = f.label :price, "値段"
      = f.text_field :price
    li
      = f.label :category_id, "カテゴリー"
      = f.select :category_id , Category.all_ary
    li
      = f.label :count, "個数"
      = f.text_field :count
    li
      = f.submit("登録する")

app/views/admin/books/show.html.slim
table
  tr
    th タイトル 
    th 著者
    th 値段
    th 個数
  tr
    td = link_to @book.title, edit_admin_book_path(@book.id)
    td = @book.author
    td = @book.price
    td = @book.count