config/routes.rb
Rails.application.routes.draw do

   #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'root#index'
   resources :books, only: [:show]
   resources :logs, only: [:destroy]
   resources :users do
     resources :logs, only: [:create, :index]
   end
   resources :categories, only: [:index,:show]
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   namespace :admin do
     resources :books
     resources :categories, only: [:new, :create]
     resources :logs, only: [:index,:show,:update,:destroy] do
       post 'toggle_confirm'
     end
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :logs, dependent: :destroy
  belongs_to :category
  scope :get_by_title, ->(title){
    where("title like ?", "%#{title}%")
  }
  scope :is_stocked, ->{ where("count > 0") }
  scope :is_published, ->{ where(is_published: 1)}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  def self.all_ary
    ary = [] 
    self.all.each do |a|
      sub_ary = [a.name,a.id]
      ary.push(sub_ary)
    end
    ary
  end
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum is_processed: {x: 0,v: 1}

  def self.get_current_user_log(user_id, book_id)
    where(user_id: user_id).where(book_id: book_id)
  end

  def book_time
    (self.created_at + 9.hours).strftime("%Y/%m/%d %H:%M")
  end

  private
    after_destroy{
      self.book.count += 1
      self.book.save
    }
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, uniqueness: { allow_blank: true }
    validates :tw_name, uniqueness:  {allow_blank: true } 
    has_secure_password
    has_many :logs, dependent: :destroy

    enum faculty: {"文学部":0, "経済学部":1, "法学部":2, "人間開発学部":3, "神道文化学部":4}
    enum department: {'日本文学科':0,'中国文学科':1, '外国語文化学科':2, '史学科':3,'哲学科':4, '経済学科':4, '経済ネットワーキング学科':6, '経営学科':7, '法律学科':8, '初等教育学科':9, '健康体育学科':10, '子ども支援学科':11, '神道文化学科':12}
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  include AdminHelper
  before_action :is_administrator?
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book
  def show
    session.delete(:requested_book_id)
    if current_user && log = Log.get_current_user_log(current_user.id, params[:id]).first
      @log = log
    else
      @log = Log.new
    end
  end

  private
    def set_book
      @book = Book.find_by(id: params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category_name = Category.find(params[:id]).name
    @books = Book.where(category_id: params[:id]).where("count > 0").page(params[:page]).per(30);
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  
  def index
   redirect_to user_logs_path(current_user.id) unless current_user.id == params[:user_id].to_i  
   @logs = Log.where(user_id: params[:user_id])
  end
  
  def create
    if logged_in?
      Log.create(log_params)  
      book = Book.find_by(id: params[:log][:book_id])
      book.update_attribute(:count,  book.count - 1)
      redirect_to root_path, notice: '予約しました。' and return
    end
    redirect_to login_path
  end

  def destroy 
    @log = Log.find_by(id: params[:id])
    if @log.present? && @log.destroy
      redirect_to root_path, notice: '予約をキャンセルしました。'
    else
      redirect_to user_logs_path(current_user.id), alert: "キャンセルできませんでした。"
    end
  end

  private
    def log_params
      params.require(:log).permit(:user_id, :book_id,:count)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    if params[:title].present?
      @books = Book.get_by_title(params[:title]).is_stocked.is_published
      @books = @books.page(params[:page]).per(30)
    else
      @books = Book.is_stocked.is_published
      @books = @books.page(params[:page]).per(30)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to book_path(session[:requested_book_id]) and return if session[:requested_book_id].present?
        redirect_to user
      else
        flash.now[:danger] = 'emailまたはパスワードが違います'
        render 'new'
      end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]

  def show
    unless params[:id].to_i == current_user.id 
      redirect_to user_path(current_user.id)
    end
  end

  def edit
  end

  def new
   @user = User.new 
  end

  def create
    @user =  User.new(user_params)  
    if @user.save
      log_in @user
      redirect_to @user 
    else
      flash[:danger] = '必要な項目を入力してください'
      render "new"
    end
  end

  def update
    @user.update!(user_params)
    redirect_to @user
  end

  private
    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit!
    end
end

app/helpers/admin_helper.rb
module AdminHelper

  def admin_logout
    session[:admin] = nil
  end

  def is_administrator?
    unless current_user.present? && current_user.email == ENV['ADMIN_EMAIL']
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: Settings.meta.name,
      charset: 'utf-8',
      title: Settings.meta.title,
      description: Settings.meta.description,
      keywords: Settings.meta.keywords,
      canonical: request.original_url,
      og: {
        type: Settings.meta.og.type,
        title: :title,
        description: :description,
        url: request.original_url,
        site_name: :site,
        image: "http://sftkoku.tokyo/#{asset_path("sft_logo3_1.png")}",
      },
      twitter: {
        card: 'summary_large_image',
        title: 'SFT國學院オンライン教科書予約',
        desciption: :description,
        creator: '@sftkoku',
        image: "http://sftkoku.tokyo/#{asset_path("sft_logo3_1.png")}"
      }
    }
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def book_or_not_btn
    if current_user.book
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def books_or_not
    if @books.empty?
     render partial: "shared/no_book" 
    else
     render partial: "shared/book_list" , locals: {books: @books}
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_books_index.html.erb
<table class="admin_books">
  <thead>
    <th>タイトル</th>
    <th>著者</th>
    <th>値段</th>
    <th>個数</th>
  </thead>
  <tbody>
  <% books.each do |book| %>
  <tr>
    <td><%= link_to book.title, edit_admin_book_path(book.id) %></td>
    <td><%= book.author %></td>
    <td><%= book.price %></td>
    <td><%= book.count %></td>
  </tr>
  <% end %>
 </tbody>
</table>

app/views/layouts/admin.html.slim
head
  = csrf_meta_tags
  meta name="viewport" content="width=device-width,initial-scale=1" 
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = javascript_include_tag 'jquery'

body
  = render "shared/flash"
  = yield

  footer 
    ul.admin_footer
      li
        = link_to(root_path) do
          =fa_icon "2x home"
      li
        = link_to(admin_books_path) do
          = fa_icon "2x list"
      li 
        = link_to(admin_logs_path) do 
          = fa_icon "2x book"
      li 
        = link_to(new_admin_book_path) do
          = fa_icon "2x plus"

app/views/layouts/application.html.slim
doctype html
html
  head
    <!-- Global site tag (gtag.js) - Google Analytics -->
    script{ async src="https://www.googletagmanager.com/gtag/js?id=UA-116918305-1" }
    javascript:
      window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-116918305-1');
    = csrf_meta_tags
    = display_meta_tags(default_meta_tags)
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div.bottom_fixed
    = render "shared/flash"
    = yield
    footer
      ul.head_menu
        li
          = link_to(root_path) do
            = fa_icon "2x home"
        li
          = link_to(categories_path) do
            = fa_icon "2x search"
        - if logged_in?
          li
            = link_to(user_logs_path(current_user.id)) do
              = fa_icon "2x book"
          li
            = link_to(user_path(session[:user_id])) do
              = fa_icon "2x user"
        - else
          li
            = link_to(login_path) do
              = fa_icon "2x book"
          li
            = link_to(login_path) do
              = fa_icon "2x sign-in"

app/views/shared/_book_list.html.slim
div.book_list
  div.book_container
    - books.each do |book| 
      - unless book.image.url.nil?
        div.container
          =link_to book_path(book.id) do
            div.img_container style="background-image: url(#{asset_path (book.image.thumb.url)})"
            h2 #{book.title}

app/views/shared/_flash.html.slim
- if flash.present?
  div.errors
    -flash.each do |key, value| 
      =content_tag(:div, value, class: "#{key}") 

app/views/shared/_log_table.html.slim
ul.admin_logs_show
  li ユーザー名
  li = log.user.name
  li mail| twitter 
  - if log.user.tw_name.present?
    li 
      a href="http://twitter.jp/#{log.user.tw_name}" @#{log.user.tw_name}
  - else 
    li = log.user.email
  - if log.book.present?
    li 教科書名
    li = log.book.title
    li 値段
    li ¥#{log.book.price}

app/views/shared/_login_form.html.erb
  <%= form_for(:session, url: login_path) do |f|  %>
    <div class="form-item">
      <label for="email"></label>
      <%= f.email_field :email, class: "form_item", placeholder: "email" %>
    </div>
    <div class="form-item">
      <label for="password"></label>
      <%= f.password_field :password, class: "form_item", placeholder: "password"  %>
    </div>
    <div class="button-panel">
      <%= f.submit "ログイン", class: "button" %>
    </div>
  <% end %>

app/views/shared/_no_book.html.slim
.no_book_container
  p 
    | ごめんなさい！教科書の在庫がありません。
    br
    br
    | Study For Twoでは
    br
    |使わなくなった教科書の回収も行なっています。
    br
    | お気軽にお問い合わせください。

  =link_to "カテゴリーへ戻る", categories_path, class: 'category_back_btn'

app/views/shared/_result_no_book.html.slim
.no_book_container
  p 
    | 条件に合う教科書が見つかりません。
    br
    | お手数ですが以下の例も参考にしてみてください。
    br
    br
    | × ぷれすてっぷ
    br
    | ○ プレステップ

app/views/shared/_toggle_confirm_form.html.erb
<%= form_for log, { url: admin_log_path(log.id)} do |f| %> 
  <%= f.hidden_field :user_id, value: session[:user_id] %>
  <%= f.hidden_field :book_id , value: log.book.id %>
  <%= f.hidden_field :count , value: log.book.count %>
  <%= f.hidden_field :is_processed, value: log.is_processed %>  
  <%= f.submit("確認反転する", class:"button_orange") %>
<% end %>

app/views/shared/_user_register_form.html.slim
ul.form-item
  li
     = f.label :name, "名前" 
     =f.text_field :name 
  li 
     = f.label :name, "email"
     =f.text_field :email 
  li 
     = f.label :name, "パスワード"
     =f.password_field :password
  li
     = f.label :name, "パス確認"
     =f.password_field :password_confirmation
  li
     = f.label :name, "学部"
     = f.select :faculty, User.faculties.keys.to_a, {}
  li
     = f.label :name, "学科"
     =f.select :department,  User.departments.keys.to_a, {}
  li
     = f.label :name, "学年"
     = f.select :year, [1,2,3,4,]
  li
     = f.label :name, "Twitterアカウント名"
     = f.text_field :tw_name
  br
  p 
     |記入された場合は、予約された際DMにて連絡するために使用いたします。
     br
     |一般には公開されません。
  li.button-panel = f.submit("登録", class: "button") 